--- 
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: sim-k8s-agent
spec:
  selector:
    matchLabels:
      name: sim-k8s-agent   
  template: 
    metadata: 
      labels: 
        name: sim-k8s-agent
    spec:
      containers:
      - envFrom:
         - configMapRef:
             name: appd-app-config
        env:
        - name: APPDYNAMICS_SIM_ENABLED
          value: "true"
        - name: APPDYNAMICS_DOCKER_ENABLED
          value: "true"
        - name: APPDYNAMICS_AGENT_ENABLE_CONTAINERIDASHOSTID
          value: "true"
        image: appdynamics/machine-agent-analytics:latest
        imagePullPolicy: Always
        name: sim-k8s-agent
        resources: {}
        volumeMounts:
        - mountPath: /hostroot
          name: hostroot
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: docker-sock
      restartPolicy: Always
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket

---
apiVersion: v1
kind: Service
metadata:
  name: analytics-agent
spec:
  selector:
    name: sim-k8s-agent
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
status:
  loadBalancer: {}