apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  appName: "JSCHN86d-AD-Fin-PostMod"
  controllerUrl: "https://aws-sandbox.saas.appdynamics.com"
  account: "aws-sandbox"
  # docker image info
  image: "appdynamics/cluster-agent:latest"
  serviceAccountName: appdynamics-cluster-agent
  ### Uncomment the following two lines if you need pull secrets
  #imagePullSecrets:
  #  name: "<your-docker-pull-secret-name>"