apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: AD-Fin-PostMod-JRSHN874a
  region: us-west-1
  version: "1.17"

availabilityZones: ["us-west-1a", "us-west-1b"]

managedNodeGroups:
- name: nodegroup
  instanceType: m5a.large
  desiredCapacity: 2

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: appd-app-services
      # if no namespace is set, "default" will be used;
      # the namespace will be created if it doesn't exist already
      # namespace: default
      labels: {aws-usage: "application"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    - "arn:aws:iam::aws:policy/AmazonRDSFullAccess"


# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]
